### ISSUE TITLE
Draft articles are being displayed

### ISSUE THREAD

**Issue by jimmylevell** [scout-ch/thilo-api#37]
Goal is that sections which are not published, should not be displayed within Thilo.

**Comment by jimmylevell** [comment]
Within strapi this somehow cannot be implemented as standard. So there is not an option I have found to only return published sections. 

@broesmel : could you filter within the frontend that you only display sections if they have a publishing date? 

Not published example: 
         "published_at": null,

Published example:
        "published_at": "2023-08-28T05:40:02.731Z",

Endpoint: https://strapi.app.levell.ch/sections?_locale=de

**Comment by broesmel** [comment]
Will be solved in the front-end using the `published_at` tag.

**Comment by jimmylevell** [comment]
@bodobraegger : konntest du dies bereits anschauen?

**Comment by jimmylevell** [comment]
@bodobraegger konntest du dies bereits anschauen?

**Comment by bodobraegger** [comment]
Commit b748c305895a5da22b967925c7708c225fee47af has solved this issue, as is evident when accessing the page.
